### ISSUE TITLE
无法编码的 Unicode 字符

### ISSUE THREAD

**Issue by bkzy333** [BNDou/Auto_Check_In#36]
夸克自动签到有无法编码的字符（省略号），青龙面板运行后，出现以下错误
`Traceback (most recent call last):
  File "/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_Quark.py", line 141, in <module>
    main()
  File "/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_Quark.py", line 124, in main
    log = Quark(cookie_quark[i]).do_sign()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_Quark.py", line 88, in do_sign
    account_info = self.get_account_info()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_Quark.py", line 79, in get_account_info
    response = requests.request("GET", url, headers=headers, params=querystring).json()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 399, in request
    self.putheader(header, value)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 313, in putheader
    super().putheader(header, *values)
  File "/usr/local/lib/python3.11/http/client.py", line 1267, in putheader
    values[i] = one_value.encode('latin-1')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2026' in position 512: ordinal not in range(256)`

**Comment by BNDou** [comment]
你这个情况我没遇到过，可能与青龙环境的版本有关系，也可能与你的cookie有关系。

我尝试加了几行代码，你更新一下看看能否解决。

如果还是这样，如果你不介意😂可以把cookie分享给我测试，回头重登账号就可以刷新cookie了
