### ISSUE TITLE
恩山签到出现这个问题，麻烦看看是缺少依赖吗

### ISSUE THREAD

**Issue by duolingmi** [BNDou/Auto_Check_In#52]
Traceback (most recent call last):
  File "/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_EnShan.py", line 16, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'

**Comment by BNDou** [comment]
@duolingmi 去青龙的依赖管理中安装Python的 `lxml`
![mmexport1721461114803.png](https://github.com/user-attachments/assets/1cda67f1-e0fb-4adc-84eb-4e1dda202a7b)

**Comment by duolingmi** [comment]
谢谢，恩山论坛签到搞定了。脚本猫签到还是有问题。
## 开始执行... 2024-07-21 12:02:30

----------脚本猫论坛开始尝试签到----------
Traceback (most recent call last):
  File "/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_ScriptCat.py", line 125, in <module>
    log += ScriptCat(cookie_ScriptCat[i]).main()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_ScriptCat.py", line 100, in main
    self.get_log()
  File "/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_ScriptCat.py", line 88, in get_log
    self.leijiqiandao = html.xpath('//b//text()')[1]
                        ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

## 执行结束... 2024-07-21 12:02:36  耗时 6 秒

**Comment by BNDou** [comment]
@duolingmi 
一定要抓取签到请求，今天已经签过就没法抓了，明天你试试，url是
 
`https://bbs.tampermonkey.net.cn/plugin.php?id=dsu_paulsign:sign`

问号后面的参数也是要有的，把这个请求的cookie做环境变量试试。
筛去无用的cookie，也就是只需要这俩个值就能签到

`B6hk_2132_saltkey=xxxx; B6hk_2132_auth=xxxx;`

**Comment by duolingmi** [comment]
谢谢了。又试了3次，还是有问题，如果签到以后，再测试日志会出现已签到。但是不签到运行还是出现这样的问题。
## 开始执行... 2024-07-24 07:32:57

----------脚本猫论坛开始尝试签到----------
Traceback (most recent call last):
  File "/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_ScriptCat.py", line 125, in <module>
    log += ScriptCat(cookie_ScriptCat[i]).main()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_ScriptCat.py", line 100, in main
    self.get_log()
  File "/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_ScriptCat.py", line 95, in get_log
    self.date = html.xpath('//p[3]/font//text()')[0]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by BNDou** [comment]
@duolingmi 你是说第一天运行日志出现已签到的字样时，同样的ck在第二天签到，还是会出现这样的异常吗？如果是的话，那可能还是没抓对。我之前测试过两个号都是直接成功的，直到现在也是正常运行。等我回头再测试一下抓包流程

**Comment by duolingmi** [comment]
是的，每天都重新抓取，没有成功的时候
