### ISSUE TITLE
夸克签到要抓取哪个请求的cookie

### ISSUE THREAD

**Issue by formyangel1219** [BNDou/Auto_Check_In#53]
提示信息：
--夸克网盘开始签到----------
✅ 检测到共 1 个夸克账号

Traceback (most recent call last):
  File "/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_Quark.py", line 204, in <module>
    main()
  File "/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_Quark.py", line 187, in main
    log = Quark(user_data).do_sign()
  File "/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_Quark.py", line 159, in do_sign
    log += f"❌ 签到异常: 获取成长信息失败"
UnboundLocalError: local variable 'log' referenced before assignment

**Comment by formyangel1219** [comment]
已在代码中找到方法，3q
