### ISSUE TITLE
夸克出现问题，麻烦看看

### ISSUE THREAD

**Issue by zero890628** [BNDou/Auto_Check_In#58]
----------夸克网盘开始签到----------
✅ 检测到共 1 个夸克账号

Traceback (most recent call last):
  File "/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_Quark.py", line 224, in <module>
    main()
  File "/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_Quark.py", line 207, in main
    log = Quark(user_data).do_sign()
  File "/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_Quark.py", line 174, in do_sign
    balance = self.queryBalance()
  File "/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_Quark.py", line 137, in queryBalance
    return response["msg"]
KeyError: 'msg'

**Comment by BNDou** [comment]
@zero890628 订阅更新一下再试试

**Comment by fbt9910** [comment]
> ----------夸克网盘开始签到---------- ✅ 检测到共 1 个夸克账号
> 
> 回溯（最近一次调用最后一次）： 文件“/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_Quark.py”，第 224 行，在 main() 中文件“/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_Quark.py”，第 207 行，在主 日志中 = Quark(user_data).do_sign() 文件“/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_Quark.py”，第 174 行，在 do_sign 中 余额 = self.queryBalance() 文件“/ql/data/scripts/BNDou_Auto_Check_In_main/checkIn_Quark.py”，第 137 行，在 queryBalance 中 返回响应[“msg”] KeyError：'msg'

测试正常
